"""empty message

Revision ID: 4e47f65a5365
Revises: cd3cd122d1f3
Create Date: 2026-09-20 13:52:43.173310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e47f65a5365'
down_revision = 'cd3cd122d1f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('home_state', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('home_state')
        batch_op.drop_column('home_country')

    # ### end Alembic commands ###
